---
title: "Shiny_SBCLTER"
author: "Terra Dressler"
date: "January 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Load Packages
```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(leaflet)
library(sf)
library(tmap)
library(ggspatial)
library(ggrepel)
```
 
2. Read in Fish Data

```{r, warning = FALSE, message = FALSE}

SitePoints <- read_csv("Site_GPS.csv")
fish <- read_csv("All_Fish_All_Years_20171201.csv")
```

3. Data merging and wrangling, density calculations

```{r, warning = FALSE, message = FALSE}

SitePoints_edit<- SitePoints %>% 
  rename(site = SiteName)

FishSummary <- fish %>% 
  select(year, month, date, site, transect, SIZE, COUNT, AREA, COMMON_NAME) %>%
  filter(COMMON_NAME != "-99999", COMMON_NAME != "no fish present", COUNT != -99999) %>% 
  group_by(site, year, COMMON_NAME) %>% 
  summarise(SUM =sum(COUNT)) %>% 
  mutate(density = SUM/80) %>% 
  filter(SUM != -99984 | SUM != -99971 | SUM != -99997)


fulldatafish = merge(FishSummary, SitePoints_edit)
  
fulldatafish_sf <- st_as_sf(fulldata, coords = c("LONG", "LAT"), crs = 4326)

```

4. Temperature data wrangling, merging

```{r, warning = FALSE, message = FALSE}
temp_short <-read_csv("bottom_temp_all_years_20171201.csv") %>% 
  separate(Date, c("y", "m", "d")) %>% 
  group_by(site, y) %>%
  summarise(mean_temp = mean(temp_c)) %>% 
  rename(year = y)

write.csv(temp_short, "tempdata_shortened.csv")
  

fulldata_temp <- merge(fulldata, temp_short)

fulldata_sf <- st_as_sf(fulldata_temp, coords = c("LONG", "LAT"), crs = 4326)

```


5. Mapping data

```{r}
#Mapping practice
fulldata_kb_2017 <- fulldata_sf %>% 
  filter(year == 2017, COMMON_NAME == "Kelp Bass") %>% 
  mutate(size = density*50)

fishIcons <- iconList( fish = makeIcon("fish.png", 18, 18) )

map1 <- leaflet(fulldata_sf) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(color = "orange", fillOpacity = fulldata_sf$mean_temp)
  addCircleMarkers(map1, color = "darkmagenta", radius = fulldata_sf$density)

map1
```


6. Plot

```{r}

plot <- fulldata_sf %>% 
  filter(COMMON_NAME == "Kelp Bass", site == "ABUR") %>% 
  ggplot(aes(x = year, y = density))+
         geom_col(position = position_dodge(0), fill = "darkmagenta" )+
  labs(x = "Year", y= "Observed Fish Density")+
  scale_y_continuous(sec.axis = sec_axis(~.+14, name = "Mean Yearly Temperature (Celcius)"))
  
  


plot
               
    
```






```

